### ISSUE TITLE
Doesn't work on Angular5

### ISSUE THREAD

**Issue by edmondko** [sollenne/ng4-fittext#8]
```

WARNING in C:/xampp/htdocs/webpages/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\webpack\lib\dep
endencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\webpack\l
ib\Compilation.js:703:24)
    at Compilation.finish (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\webpack\lib\Compiler.js:506:17
)
    at C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\tapable\lib\Tapable.js:289:11
    at C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\html-webpack-plugin\index.js:60:9
    at tryCatcher (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\p
romise.js:512:31)
    at Promise._settlePromise (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\promise.js:5
69:18)
    at Promise._settlePromise0 (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\promise.js:
614:10)
    at Promise._settlePromises (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\promise.js:
693:18)
    at Async._drainQueue (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\async.js:143:10)

    at Immediate.Async.drainQueues (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\async.j
s:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
 @ C:/xampp/htdocs/webpages/node_modules/@angular/core/@angular/core.es5.js
 @ C:/xampp/htdocs/webpages/node_modules/ng4-fittext/ng4-fittext/ng4-fittext.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in C:/xampp/htdocs/webpages/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\webpack\lib\dep
endencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\webpack\l
ib\Compilation.js:703:24)
    at Compilation.finish (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\webpack\lib\Compiler.js:506:17
)
    at C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\tapable\lib\Tapable.js:289:11
    at C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\html-webpack-plugin\index.js:60:9
    at tryCatcher (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\p
romise.js:512:31)
    at Promise._settlePromise (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\promise.js:5
69:18)
    at Promise._settlePromise0 (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\promise.js:
614:10)
    at Promise._settlePromises (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\promise.js:
693:18)
    at Async._drainQueue (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\async.js:143:10)

    at Immediate.Async.drainQueues (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\bluebird\js\release\async.j
s:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
 @ C:/xampp/htdocs/webpages/node_modules/@angular/core/@angular/core.es5.js
 @ C:/xampp/htdocs/webpages/node_modules/ng4-fittext/ng4-fittext/ng4-fittext.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by sollenne** [comment]
I'll update shortly

**Comment by sollenne** [comment]
Just updated for latest angular 5.0.1 
```
npm i ng4-fittext@latest --save-dev
```
